from __future__ import annotations

import re

# All AWS Pricing Calculator page text lives here so UI changes are maintained
# in one place instead of being scattered through quote business logic.
ADD_SERVICE_URL = "https://calculator.aws/#/addService"
SERVICE_SEARCH = re.compile(r"查找服务|Find service", re.I)
CONFIGURE_EC2 = re.compile(r"配置 Amazon EC2|Configure Amazon EC2", re.I)
CONFIGURE_RDS = re.compile(r"配置 Amazon RDS|Configure Amazon RDS", re.I)
REGION_BUTTON = re.compile(r"选择一个区域|Choose a region", re.I)
INSTANCE_QUANTITY = re.compile(r"实例数量|Number of instances", re.I)
INSTANCE_SEARCH = re.compile(r"Search instance types|搜索实例类型", re.I)
VCPU_FILTER = re.compile(r"vCPU 数|vCPUs", re.I)
MEMORY_FILTER = re.compile(r"内存\(GiB\)|Memory \(GiB\)", re.I)
EC2_SELECTION_TABLE = re.compile(r"EC2 selection", re.I)
ON_DEMAND = re.compile(r"按需实例|On-Demand", re.I)
SPOT = re.compile(r"竞价型实例|Spot Instances", re.I)
COMPUTE_SAVINGS_PLAN = re.compile(r"Compute Savings Plans", re.I)
EC2_SAVINGS_PLAN = re.compile(r"EC2 Instance Savings Plans", re.I)
STANDARD_RESERVED = re.compile(r"标准预留实例|Standard Reserved", re.I)
CONVERTIBLE_RESERVED = re.compile(r"可转换预留实例|Convertible Reserved", re.I)
OTHER_PURCHASE_OPTIONS = re.compile(r"其他购买选项|Other purchase options", re.I)
TERM_1_YEAR = re.compile(r"1 year", re.I)
TERM_3_YEAR = re.compile(r"3 year", re.I)
NO_UPFRONT = re.compile(r"无预付费用|No upfront", re.I)
PARTIAL_UPFRONT = re.compile(r"预付部分费用|Partial upfront", re.I)
ALL_UPFRONT = re.compile(r"预付全部费用|All upfront", re.I)
UTILIZATION = re.compile(r"使用情况|Utilization", re.I)
EBS_SECTION = re.compile(r"^Amazon Elastic Block Store.*(?:可选|optional).*$", re.I)
EBS_STORAGE = re.compile(r"存储量.*值|Storage amount.*Value", re.I)
EBS_VOLUME_TYPE = re.compile(r"每个 EC2 实例的存储|Storage for each EC2 instance", re.I)
EBS_IOPS = re.compile(r"IOPS.*(?:输入每卷|per volume)", re.I)
EBS_THROUGHPUT = re.compile(r"吞吐量.*值|Throughput.*Value", re.I)
SNAPSHOT_FREQUENCY = re.compile(r"快照拍摄频率|Snapshot frequency", re.I)
SNAPSHOT_CHANGED = re.compile(r"每个快照的更改量.*值|Change per snapshot.*Value", re.I)
DETAILED_MONITORING_SECTION = re.compile(r"^详细监控.*可选|Detailed monitoring.*optional", re.I)
ENABLE_MONITORING = re.compile(r"启用监控|Enable monitoring", re.I)
DATA_TRANSFER_SECTION = re.compile(r"^数据传输.*可选|Data transfer.*optional", re.I)
INBOUND_SOURCE = re.compile(r"入站数据传输.*(?:从|From)|Inbound.*From", re.I)
OUTBOUND_DESTINATION = re.compile(r"出站数据传输.*(?:到|To)|Outbound.*To", re.I)
INTERNET_OPTION = re.compile(r"Internet|互联网", re.I)
INBOUND_TRANSFER_UNIT = re.compile(r"入站数据传输.*数据量|Inbound.*Data amount", re.I)
REGIONAL_TRANSFER_UNIT = re.compile(r"区域内数据传输.*数据量|Regional.*Data amount", re.I)
OUTBOUND_TRANSFER_UNIT = re.compile(r"出站数据传输.*数据量|Outbound.*Data amount", re.I)
GB_PER_MONTH_LABELS = {"gb/月", "gb/month"}
ADDITIONAL_COST_SECTION = re.compile(r"^额外费用.*可选|Additional cost.*optional", re.I)
ADDITIONAL_COST_INPUT = re.compile(r"占位符成本|placeholder cost", re.I)
SAVE_SUMMARY = re.compile(r"保存并查看摘要|Save and view summary", re.I)
SAVE_ADD_SERVICE = re.compile(r"保存并添加服务|Save and add service", re.I)
SUMMARY_MONTHLY_TOTAL = re.compile(
    r"(?:每月成本|Monthly cost)\s*:?\s*([0-9,]+(?:\.[0-9]+)?)\s*USD",
    re.I,
)
SUMMARY_UPFRONT_TOTAL = re.compile(
    r"(?:预付成本|Upfront cost)\s*:?\s*([0-9,]+(?:\.[0-9]+)?)\s*USD",
    re.I,
)
ESTIMATE_SERVICES_TABLE = re.compile(r"Estimate Services Table", re.I)
SUMMARY_MONTHLY = re.compile(r"每月成本|Monthly cost", re.I)
SHARE = re.compile(r"分享|Share", re.I)
AGREE_SHARE = re.compile(r"同意并继续|Agree and continue", re.I)
PUBLIC_LINK = re.compile(r"复制公共链接|Copy public link", re.I)
PUBLIC_LINK_INPUT = 'input[value^="https://calculator.aws/#/estimate?id="]'

# Amazon RDS pages share these semantic labels across database engines.
RDS_NODES = re.compile(r"^节点$|Nodes", re.I)
RDS_INSTANCE = re.compile(r"Select an instance|选择实例", re.I)
RDS_DEPLOYMENT = re.compile(r"部署选项|Deployment option", re.I)
RDS_PRICING_MODEL = re.compile(r"定价模型|Pricing model", re.I)
RDS_UTILIZATION = re.compile(r"利用率（仅限按需） 值|Utilization.*Value", re.I)
RDS_STORAGE_TYPE = re.compile(r"每个 RDS 实例的存储|Storage per RDS instance", re.I)
RDS_STORAGE_AMOUNT = re.compile(r"存储量 值|Storage amount.*Value", re.I)
RDS_STORAGE_UNIT = re.compile(r"单位 存储量|Storage amount.*Unit", re.I)
RDS_LICENSE = re.compile(r"^许可证|^License", re.I)
RDS_LICENSE_INCLUDED = re.compile(r"License included|许可包含", re.I)
RDS_BRING_YOUR_OWN_MEDIA = re.compile(r"Bring your own media|自带介质", re.I)
RDS_DATABASE_VERSION = re.compile(r"数据库版本|Database version", re.I)
RDS_SQL_STANDARD = re.compile(r"^Standard$|^标准版$", re.I)
RDS_SQL_WEB = re.compile(r"^Web$|^Web 版$", re.I)
RDS_SQL_ENTERPRISE = re.compile(r"^Enterprise$|^企业版$", re.I)
RDS_MULTI_AZ = re.compile(r"^Multi-AZ$", re.I)
RDS_SINGLE_AZ = re.compile(r"^Single-AZ$", re.I)
RDS_ON_DEMAND = re.compile(r"OnDemand|On-Demand", re.I)
RDS_RESERVED = re.compile(r"Reserved", re.I)
RDS_TERM_FIELD = re.compile(r"^期限|^Term", re.I)
RDS_TERM_1_YEAR = re.compile(r"1yr|1\s*year|1\s*年", re.I)
RDS_TERM_3_YEAR = re.compile(r"3yr|3\s*year|3\s*年", re.I)
RDS_PURCHASE_FIELD = re.compile(r"购买选项|Purchase option|Payment option", re.I)
RDS_NO_UPFRONT = re.compile(r"No Upfront|无预付", re.I)
RDS_PARTIAL_UPFRONT = re.compile(r"Partial Upfront|部分预付", re.I)
RDS_ALL_UPFRONT = re.compile(r"All Upfront|全预付", re.I)
RDS_PROXY = re.compile(r"您希望使用数据库创建 RDS 代理吗|RDS Proxy", re.I)
RDS_DATABASE_INSIGHTS = re.compile(r"启用 Database Insights|enable Database Insights", re.I)
RDS_EXTENDED_SUPPORT = re.compile(r"是否计划运行扩展支持|extended support", re.I)
RDS_NO = re.compile(r"^否$|^No$", re.I)
